### ISSUE TITLE
I have this problem if i try to compute de concise workflow

### ISSUE THREAD

**Issue by AndreaCa96** [Zquinlan/ecoNet#2]
Exception in thread Thread-7:
Traceback (most recent call last):
  File "threading.py", line 980, in _bootstrap_inner
  File "threading.py", line 917, in run
  File "workflowMain.py", line 94, in runWorkFlow
  File "conCISE.py", line 278, in __init__
  File "conCISE.py", line 256, in filterClassy
  File "pandas\util\_decorators.py", line 331, in wrapper
  File "pandas\core\frame.py", line 6558, in dropna
KeyError: ['superclass_annotation', 'class_annotation', 'subclass_annotation']

**Comment by Zquinlan** [comment]
Hi! Someone else just had the same issue earlier this week. It was caused by GNPS no longer having the classification breakdown (superclass, class, subclass) from classyfire and only supplying NPClassifier breakdown. I am not sure if this is a permanent change or a temporary error. 

In the next couple of days I will release an updated version of concise which will allow NPClassifier to be used as an option. If you're in a crunch to have the data before Monday, I am happy to manually run your data through concise using NPClassifier.

**Comment by AndreaCa96** [comment]
Thank you for your reply! I can wait.

Many thanks
