### ISSUE TITLE
Issues with GUI and Binder notebook and Sirius 6

### ISSUE THREAD

**Issue by silasmellor** [Zquinlan/ecoNet#9]
Hi Zach, 
First of all, thanks for putting such a useful tool out there, really great. I am running into an issue however trying to merge a FBMN/GNPS job with Canopus annotations from Sirius 6. When i try doing so with the GUI i get the following error:

```
Exception in thread Thread-1 (runWorkFlow):
Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3805, in get_loc
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'name'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "workflowMain.py", line 37, in runWorkFlow
  File "pandas\core\frame.py", line 4102, in __getitem__
  File "pandas\core\indexes\base.py", line 3812, in get_loc
KeyError: 'name'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pandas\core\indexes\base.py", line 3805, in get_loc
  File "index.pyx", line 167, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 196, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7081, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\\_libs\\hashtable_class_helper.pxi", line 7089, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "workflowMain.py", line 39, in runWorkFlow
  File "pandas\core\frame.py", line 4102, in __getitem__
  File "pandas\core\indexes\base.py", line 3812, in get_loc
KeyError: 'id'
```

Is this because the GUI does not recognize the new format of the canopus summary reports?

I tried using the Binder notebook, but get another error instead:

```
Traceback (most recent call last):
  File "/home/jovyan/src/conciseCLI.py", line 4, in <module>
    from workflowMain import *
  File "/home/jovyan/src/workflowMain.py", line 36
    try: 
         ^
IndentationError: unindent does not match any outer indentation level
```

Best,
Silas

**Comment by Zquinlan** [comment]
Hey Silas,

You are spot on that this is an issue with the new SIRIUS column name. I tried to patch it a week ago but the line that fixed it had an indentation issue (hence the myBinder error). Thanks for catching that.

I just pushed the fixed code and you can now download the new gui [here](https://github.com/Zquinlan/conCISE/releases/download/v1.20/conciseGui.exe).

Let me know if you still run into issues with this GUI.

**Comment by silasmellor** [comment]
Hey Zach, that was quick! I am just on my way to bed (its nearly midnight here) but i will give it a try first thing tomorrow and report back.

thanks,
Silas

**Comment by silasmellor** [comment]
Hi Zach, Just tested and the latest 1.21 now works with Sirius 6, thanks again for the quick fix!
Best,
Silas
